name: CI
on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

  workflow_dispatch:

jobs:
  test:
    name: build
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Setup
        working-directory: test
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"

      - name: Test
        working-directory: test
        run: bats/bin/bats .
