on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Check ports
        run:
          netstat -ltnp | grep -w ':8787'

      - name: Test
        working-directory: test
        run: |
          echo $GITHUB_WORKSPACE
          bats/bin/bats .

