on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Test
        run: |
           cd test
           bats/bin/bats .      
