on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Test
        working-directory: test
        run: |
          echo $GITHUB_WORKSPACE
          bats/bin/bats help.bats
          cat .test-server.pid

